export const INDIAN_STATES = [
  "All India",
  "Central Government",
  "Multiple States",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman & Nicobar",
  "Chandigarh",
  "Dadra & Nagar Haveli",
  "Daman & Diu",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Lakshadweep",
  "Puducherry",
  "Ladakh",
  "Remote / Online",
];

export const JOBS_CATEGORIES = [
  "Government Jobs",
  "Competitive Exams",
  "State Updates",
  "UPSC",
  "SSC",
  "PSC Jobs",
  "Bank Jobs",
  "Railway Jobs",
  "Teaching Jobs",
  "Defence Jobs",
  "Police Jobs",
  "Medical Jobs",
  "Engineering Jobs",
  "Apprenticeship",
  "Scholarship",
  "Admit Card",
  "Result",
  "Answer Key",
  "Syllabus",
];
